### ISSUE TITLE
Explore flutter vs react

### ISSUE THREAD

**Issue by cicelybeckford** [PeaceA/Senior-Project#19]

**Comment by nelly2daworld** [comment]
I was reading through a few articles and it seems like Flutter is the clear winner! The thing that stuck out to me the most is you can achieve the same functionality as React Native with far lesser code. Which would be a win-win for us. Also, if you know Javascript or Java it is fairly easy to pick up Flutter.

For React native, they mentioned that it has been in the industry far longer, so it is more recognized and widely used; however, in a survey, Flutter ranked higher in preference to React native by coders. One of the reason is because Flutter has more UI and APIs embedded in the platform! Here are 3 links that stuck out the most for more in depth info:1. https://levelup.gitconnected.com/flutter-vs-native-vs-react-native-mobile-development-what-to-choose-fe3bc59910bc 2. https://medium.com/@adhithiravi/react-native-vs-flutter-what-are-the-differences-b6dc892f0d34 3. https://nevercode.io/blog/flutter-vs-react-native-a-developers-perspective/ .
